---------------------------------------------------------------------
---- NAME:FINANCIAL.customer_new-------------------------------------
---------------------------------------------------------------------

CREATE SET TABLE FINANCIAL.customer_new ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      CUSTOMER_ID INTEGER,
      CUSTOMER_FNAME CHAR(15) CHARACTER SET LATIN NOT CASESPECIFIC,
      CUSTOMER_LNAME CHAR(15) CHARACTER SET LATIN NOT CASESPECIFIC,
      CUSTOMER_DOB DATE FORMAT 'yyyy-mm-dd',
      CUSTOMER_CITY CHAR(15) CHARACTER SET LATIN NOT CASESPECIFIC,
      CUSTOMER_STATE CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      CUSTOMER_PHONE CHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC)
UNIQUE PRIMARY INDEX ( CUSTOMER_ID );
